[package]
name = "poppy-py"
version = "0.1.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "poppy"
crate-type = ["cdylib"]

[dependencies]
poppy = { path = "../poppy" }
pyo3 = "0.20.0"
